---
version: '3.9'

volumes:
    prometheus_data: {}
    grafana_data: {}


services:
  grafana:
    image: grafana/grafana:9.1.2
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - DS_PROMETHEUS=prometheus
      - TZ="Europe/Moscow"
    networks:
      - default
    depends_on:
      - prometheus
      
  prometheus:
    image: prom/prometheus:v2.38.0
    hostname: prometheusDS_PROMETHEUS=prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default