---
- hosts: all
  become: true
  vars:
    node_exporter_version: 1.3.1

  tasks:
  - name: create prometheus group
    group:
      name: prometheus

  - name: create prometheus user
    user:
      name: prometheus
      group: prometheus

  - name: Creates directory
    file:
      path: /home/prometheus
      state: directory

  - name: download latest version of node exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
      dest: /home/prometheus/node_exporter-{{ node_exporter_version }}.tgz
      mode: 777
    become: true

  - name: unarchive node exporter
    unarchive:
      src: /home/prometheus/node_exporter-{{ node_exporter_version }}.tgz
      dest: /home/prometheus/
      owner: prometheus
      remote_src: true
    args:
      creates: /home/prometheus/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter

  - name: remove node exporter tarball
    file:
      dest: /home/prometheus/node_exporter-{{ node_exporter_version }}.tgz
      state: absent

  - name: create node exporter systemd unit file
    shell: |
      echo "[Unit]
            Description=Node exporter
            Requires=network-online.target
            After=network.target network-online.target multi-user.target
 
            [Service]
            User=prometheus
            ExecStart=/home/prometheus/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter --collector.textfile.directory=/var/lib/node_exporter/metrics
            Restart=on-failure

            [Install]
            WantedBy=default.target" > /etc/systemd/system/node_exporter.service
    args:
      creates: /etc/systemd/system/node_exporter.service

  - name: set node exporter to be enabled at boot
    systemd:
      name: node_exporter
      enabled: yes
      state: started
      daemon_reload: yes
